CREATE INDEX idx_sessions_expires ON public.user_sessions USING btree (expires_at);
CREATE INDEX idx_sessions_revoked ON public.user_sessions USING btree (revoked_at);
CREATE INDEX idx_sessions_family ON public.user_sessions USING btree (token_family_id);
CREATE INDEX idx_sessions_active ON public.user_sessions USING btree (user_id) WHERE (revoked_at IS NULL);
CREATE UNIQUE INDEX password_resets_token_hash_key ON public.password_resets USING btree (token_hash);
CREATE INDEX idx_pwresets_user ON public.password_resets USING btree (user_id);
CREATE INDEX idx_pwresets_expires ON public.password_resets USING btree (expires_at);
CREATE UNIQUE INDEX password_set_tokens_token_hash_key ON public.password_set_tokens USING btree (token_hash);
CREATE INDEX idx_pst_user ON public.password_set_tokens USING btree (user_id);
CREATE INDEX idx_pst_expires ON public.password_set_tokens USING btree (expires_at);
CREATE UNIQUE INDEX invites_code_hash_key ON public.invites USING btree (code_hash);
CREATE INDEX idx_invites_active ON public.invites USING btree (code_hash) WHERE (used_at IS NULL);
CREATE INDEX idx_invites_expires ON public.invites USING btree (expires_at);
CREATE INDEX idx_invites_call ON public.invites USING btree (call_id);
CREATE UNIQUE INDEX uq_application_per_call ON public.applications USING btree (applicant_id, call_id);
CREATE INDEX idx_applications_call_status ON public.applications USING btree (call_id, status);
CREATE INDEX idx_applications_inst ON public.applications USING btree (institution_id);
CREATE INDEX gin_applications_academic ON public.applications USING gin (academic);
CREATE INDEX gin_applications_household ON public.applications USING gin (household);
CREATE INDEX gin_applications_participation ON public.applications USING gin (participation);
CREATE INDEX gin_applications_builder ON public.applications USING gin (builder_extra);
CREATE INDEX idx_app_status_hist_app ON public.application_status_history USING btree (application_id);
CREATE INDEX idx_form_sections_call ON public.form_sections USING btree (call_id);
CREATE INDEX idx_form_fields_call ON public.form_fields USING btree (call_id);
CREATE INDEX gin_form_fields_show_if ON public.form_fields USING gin (show_if);
CREATE UNIQUE INDEX uq_form_response ON public.form_responses USING btree (application_id, field_id);
CREATE INDEX gin_form_responses_value ON public.form_responses USING gin (value);
CREATE INDEX idx_app_notes_app ON public.application_notes USING btree (application_id);
CREATE UNIQUE INDEX uq_doc_current ON public.documents USING btree (application_id, type) WHERE is_current;
CREATE INDEX idx_docs_app ON public.documents USING btree (application_id);
CREATE INDEX idx_docs_type ON public.documents USING btree (type);
CREATE INDEX idx_docs_form_field ON public.documents USING btree (form_field_id);
CREATE UNIQUE INDEX uq_call_doc_req ON public.call_document_requirements USING btree (call_id, type);
CREATE UNIQUE INDEX uq_active_assignment ON public.review_assignments USING btree (application_id, reviewer_user_id);
CREATE INDEX idx_review_assign_active ON public.review_assignments USING btree (application_id) WHERE (unassigned_at IS NULL);
CREATE INDEX idx_review_assign_reviewer_active ON public.review_assignments USING btree (reviewer_user_id) WHERE (unassigned_at IS NULL);
CREATE UNIQUE INDEX uq_criteria_key ON public.criteria USING btree (call_id, key);
CREATE UNIQUE INDEX uq_score ON public.scores USING btree (application_id, criterion_id);
CREATE INDEX idx_scores_app ON public.scores USING btree (application_id);
CREATE INDEX idx_scoring_runs_call ON public.scoring_runs USING btree (call_id);
CREATE UNIQUE INDEX ranking_results_application_id_key ON public.ranking_results USING btree (application_id);
CREATE UNIQUE INDEX uq_rank_pos_per_call ON public.ranking_results USING btree (call_id, "position");
CREATE INDEX idx_rank_call ON public.ranking_results USING btree (call_id);
CREATE UNIQUE INDEX uq_call_inst_policy ON public.call_institution_policies USING btree (call_id, institution_id);
CREATE INDEX idx_interviews_app ON public.interviews USING btree (application_id);
CREATE INDEX idx_int_part_interview ON public.interview_participants USING btree (interview_id);
CREATE UNIQUE INDEX email_templates_key_key ON public.email_templates USING btree (key);
CREATE INDEX idx_email_logs_status ON public.email_logs USING btree (status);
CREATE INDEX idx_email_logs_to ON public.email_logs USING btree (to_address);
CREATE INDEX idx_audit_entity ON public.audit_logs USING btree (entity, entity_id);
CREATE UNIQUE INDEX idx_applicants_rut_unique ON public.applicants USING btree (rut_number, rut_dv) WHERE ((rut_number IS NOT NULL) AND (rut_dv IS NOT NULL));
CREATE UNIQUE INDEX "files_metadata_storedFilename_key" ON public.files_metadata USING btree ("storedFilename");
CREATE INDEX idx_files_entity ON public.files_metadata USING btree ("entityType", "entityId");
CREATE INDEX idx_files_uploader ON public.files_metadata USING btree ("uploadedBy");
CREATE INDEX idx_files_category ON public.files_metadata USING btree (category);
CREATE INDEX idx_files_active ON public.files_metadata USING btree (active);
CREATE INDEX idx_form_sections_form ON public.form_sections USING btree (form_id);
CREATE INDEX idx_form_fields_form ON public.form_fields USING btree (form_id);
CREATE INDEX idx_milestones_call ON public.milestones USING btree (call_id, order_index);
CREATE INDEX idx_milestones_form ON public.milestones USING btree (form_id);
CREATE INDEX idx_submissions_application ON public.form_submissions USING btree (application_id);
CREATE INDEX idx_submissions_milestone ON public.form_submissions USING btree (milestone_id);
CREATE INDEX idx_submissions_form ON public.form_submissions USING btree (form_id);
CREATE UNIQUE INDEX uq_milestone_progress ON public.milestone_progress USING btree (application_id, milestone_id);
CREATE INDEX idx_progress_application ON public.milestone_progress USING btree (application_id);
CREATE INDEX idx_progress_milestone ON public.milestone_progress USING btree (milestone_id);
CREATE INDEX idx_progress_status ON public.milestone_progress USING btree (status);
CREATE INDEX idx_files_milestone_submission ON public.files_metadata USING btree (milestone_submission_id);
CREATE INDEX idx_calls_active ON public.calls USING btree (is_active) WHERE (is_active = true);
CREATE INDEX idx_calls_dates ON public.calls USING btree (start_date, end_date);
CREATE INDEX idx_milestone_progress_review_status ON public.milestone_progress USING btree (review_status);
CREATE INDEX idx_milestone_progress_reviewed_by ON public.milestone_progress USING btree (reviewed_by);
CREATE INDEX idx_calls_status ON public.calls USING btree (status);
CREATE INDEX idx_calls_is_active ON public.calls USING btree (is_active);
CREATE INDEX idx_institutions_commune ON public.institutions USING btree (commune);
CREATE INDEX idx_institutions_region ON public.institutions USING btree (region);
CREATE INDEX idx_institutions_type ON public.institutions USING btree (type);
CREATE UNIQUE INDEX email_quota_tracking_tracking_date_key ON public.email_quota_tracking USING btree (tracking_date);
CREATE INDEX idx_email_quota_date ON public.email_quota_tracking USING btree (tracking_date DESC);
CREATE INDEX idx_invites_email_sent ON public.invites USING btree (email_sent, created_at DESC) WHERE (email_sent = false);
CREATE INDEX idx_invites_call_email_sent ON public.invites USING btree (call_id, email_sent);
CREATE INDEX idx_admin_2fa_codes_email ON public.admin_2fa_codes USING btree (admin_email);
CREATE INDEX idx_admin_2fa_codes_code ON public.admin_2fa_codes USING btree (code) WHERE (used = false);
CREATE INDEX idx_admin_2fa_codes_expires ON public.admin_2fa_codes USING btree (expires_at) WHERE (used = false);
CREATE INDEX idx_admin_verification_codes_code ON public.admin_verification_codes USING btree (code, requester_user_id) WHERE (used = false);
CREATE INDEX idx_admin_verification_codes_expires ON public.admin_verification_codes USING btree (expires_at) WHERE (used = false);
CREATE INDEX idx_reviewer_verification_codes_code ON public.reviewer_verification_codes USING btree (code, requester_user_id) WHERE (used = false);
CREATE INDEX idx_reviewer_verification_codes_expires ON public.reviewer_verification_codes USING btree (expires_at) WHERE (used = false);
CREATE UNIQUE INDEX password_change_tokens_token_key ON public.password_change_tokens USING btree (token);
CREATE INDEX idx_password_change_tokens_token ON public.password_change_tokens USING btree (token) WHERE (used = false);
CREATE INDEX idx_password_change_tokens_user ON public.password_change_tokens USING btree (user_id);
CREATE INDEX idx_password_change_tokens_expires ON public.password_change_tokens USING btree (expires_at) WHERE (used = false);
CREATE INDEX idx_support_messages_application ON public.support_messages USING btree (application_id);
CREATE INDEX idx_support_messages_status ON public.support_messages USING btree (status);
CREATE INDEX idx_support_messages_created_at ON public.support_messages USING btree (created_at DESC);

-- ================================================================
-- Foreign Keys
-- ================================================================

ALTER TABLE "users" ADD CONSTRAINT "users_applicant_id_fkey" FOREIGN KEY ("applicant_id") REFERENCES "applicants" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE "user_sessions" ADD CONSTRAINT "user_sessions_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "user_sessions" ADD CONSTRAINT "user_sessions_rotated_from_session_id_fkey" FOREIGN KEY ("rotated_from_session_id") REFERENCES "user_sessions" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE "password_resets" ADD CONSTRAINT "password_resets_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "password_set_tokens" ADD CONSTRAINT "password_set_tokens_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "invites" ADD CONSTRAINT "invites_call_id_fkey" FOREIGN KEY ("call_id") REFERENCES "calls" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "invites" ADD CONSTRAINT "invites_institution_id_fkey" FOREIGN KEY ("institution_id") REFERENCES "institutions" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE "invites" ADD CONSTRAINT "invites_used_by_applicant_fkey" FOREIGN KEY ("used_by_applicant") REFERENCES "applicants" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE "invites" ADD CONSTRAINT "invites_created_by_user_id_fkey" FOREIGN KEY ("created_by_user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE "applications" ADD CONSTRAINT "applications_applicant_id_fkey" FOREIGN KEY ("applicant_id") REFERENCES "applicants" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "applications" ADD CONSTRAINT "applications_call_id_fkey" FOREIGN KEY ("call_id") REFERENCES "calls" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "applications" ADD CONSTRAINT "applications_institution_id_fkey" FOREIGN KEY ("institution_id") REFERENCES "institutions" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE "application_status_history" ADD CONSTRAINT "application_status_history_application_id_fkey" FOREIGN KEY ("application_id") REFERENCES "applications" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "application_status_history" ADD CONSTRAINT "application_status_history_actor_user_id_fkey" FOREIGN KEY ("actor_user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE "form_sections" ADD CONSTRAINT "form_sections_call_id_fkey" FOREIGN KEY ("call_id") REFERENCES "calls" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "form_fields" ADD CONSTRAINT "form_fields_call_id_fkey" FOREIGN KEY ("call_id") REFERENCES "calls" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "form_fields" ADD CONSTRAINT "form_fields_section_id_fkey" FOREIGN KEY ("section_id") REFERENCES "form_sections" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE "form_responses" ADD CONSTRAINT "form_responses_application_id_fkey" FOREIGN KEY ("application_id") REFERENCES "applications" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "form_responses" ADD CONSTRAINT "form_responses_field_id_fkey" FOREIGN KEY ("field_id") REFERENCES "form_fields" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "application_notes" ADD CONSTRAINT "application_notes_application_id_fkey" FOREIGN KEY ("application_id") REFERENCES "applications" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "application_notes" ADD CONSTRAINT "application_notes_author_user_id_fkey" FOREIGN KEY ("author_user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE "application_notes" ADD CONSTRAINT "application_notes_section_id_fkey" FOREIGN KEY ("section_id") REFERENCES "form_sections" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE "documents" ADD CONSTRAINT "documents_application_id_fkey" FOREIGN KEY ("application_id") REFERENCES "applications" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "documents" ADD CONSTRAINT "documents_validated_by_fkey" FOREIGN KEY ("validated_by") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE "documents" ADD CONSTRAINT "documents_form_field_id_fkey" FOREIGN KEY ("form_field_id") REFERENCES "form_fields" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE "call_document_requirements" ADD CONSTRAINT "call_document_requirements_call_id_fkey" FOREIGN KEY ("call_id") REFERENCES "calls" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "review_assignments" ADD CONSTRAINT "review_assignments_application_id_fkey" FOREIGN KEY ("application_id") REFERENCES "applications" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "review_assignments" ADD CONSTRAINT "review_assignments_reviewer_user_id_fkey" FOREIGN KEY ("reviewer_user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "criteria" ADD CONSTRAINT "criteria_call_id_fkey" FOREIGN KEY ("call_id") REFERENCES "calls" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "scores" ADD CONSTRAINT "scores_application_id_fkey" FOREIGN KEY ("application_id") REFERENCES "applications" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "scores" ADD CONSTRAINT "scores_criterion_id_fkey" FOREIGN KEY ("criterion_id") REFERENCES "criteria" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "scoring_runs" ADD CONSTRAINT "scoring_runs_call_id_fkey" FOREIGN KEY ("call_id") REFERENCES "calls" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "scoring_runs" ADD CONSTRAINT "scoring_runs_executed_by_fkey" FOREIGN KEY ("executed_by") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE "ranking_results" ADD CONSTRAINT "ranking_results_run_id_fkey" FOREIGN KEY ("run_id") REFERENCES "scoring_runs" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "ranking_results" ADD CONSTRAINT "ranking_results_call_id_fkey" FOREIGN KEY ("call_id") REFERENCES "calls" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "ranking_results" ADD CONSTRAINT "ranking_results_application_id_fkey" FOREIGN KEY ("application_id") REFERENCES "applications" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "call_institution_policies" ADD CONSTRAINT "call_institution_policies_call_id_fkey" FOREIGN KEY ("call_id") REFERENCES "calls" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "call_institution_policies" ADD CONSTRAINT "call_institution_policies_institution_id_fkey" FOREIGN KEY ("institution_id") REFERENCES "institutions" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "interviews" ADD CONSTRAINT "interviews_application_id_fkey" FOREIGN KEY ("application_id") REFERENCES "applications" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "interview_participants" ADD CONSTRAINT "interview_participants_interview_id_fkey" FOREIGN KEY ("interview_id") REFERENCES "interviews" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "interview_participants" ADD CONSTRAINT "interview_participants_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE "email_batches" ADD CONSTRAINT "email_batches_call_id_fkey" FOREIGN KEY ("call_id") REFERENCES "calls" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "email_batches" ADD CONSTRAINT "email_batches_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE "email_recipients" ADD CONSTRAINT "email_recipients_batch_id_fkey" FOREIGN KEY ("batch_id") REFERENCES "email_batches" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "email_recipients" ADD CONSTRAINT "email_recipients_applicant_id_fkey" FOREIGN KEY ("applicant_id") REFERENCES "applicants" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE "email_logs" ADD CONSTRAINT "email_logs_template_key_fkey" FOREIGN KEY ("template_key") REFERENCES "email_templates" ("key") ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE "email_logs" ADD CONSTRAINT "email_logs_batch_id_fkey" FOREIGN KEY ("batch_id") REFERENCES "email_batches" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE "email_logs" ADD CONSTRAINT "email_logs_applicant_id_fkey" FOREIGN KEY ("applicant_id") REFERENCES "applicants" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE "email_logs" ADD CONSTRAINT "email_logs_institution_id_fkey" FOREIGN KEY ("institution_id") REFERENCES "institutions" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE "audit_logs" ADD CONSTRAINT "audit_logs_actor_user_id_fkey" FOREIGN KEY ("actor_user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE "applicants" ADD CONSTRAINT "applicants_institution_id_fkey" FOREIGN KEY ("institution_id") REFERENCES "institutions" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE "files_metadata" ADD CONSTRAINT "fk_files_uploader" FOREIGN KEY ("uploadedBy") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE "forms" ADD CONSTRAINT "forms_parent_form_id_fkey" FOREIGN KEY ("parent_form_id") REFERENCES "forms" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE "form_sections" ADD CONSTRAINT "form_sections_form_id_fkey" FOREIGN KEY ("form_id") REFERENCES "forms" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "form_fields" ADD CONSTRAINT "form_fields_form_id_fkey" FOREIGN KEY ("form_id") REFERENCES "forms" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "milestones" ADD CONSTRAINT "milestones_call_id_fkey" FOREIGN KEY ("call_id") REFERENCES "calls" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "milestones" ADD CONSTRAINT "milestones_form_id_fkey" FOREIGN KEY ("form_id") REFERENCES "forms" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE "form_submissions" ADD CONSTRAINT "form_submissions_application_id_fkey" FOREIGN KEY ("application_id") REFERENCES "applications" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "form_submissions" ADD CONSTRAINT "form_submissions_form_id_fkey" FOREIGN KEY ("form_id") REFERENCES "forms" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE "form_submissions" ADD CONSTRAINT "form_submissions_milestone_id_fkey" FOREIGN KEY ("milestone_id") REFERENCES "milestones" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE "form_submissions" ADD CONSTRAINT "form_submissions_submitted_by_fkey" FOREIGN KEY ("submitted_by") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE "milestone_progress" ADD CONSTRAINT "milestone_progress_application_id_fkey" FOREIGN KEY ("application_id") REFERENCES "applications" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "milestone_progress" ADD CONSTRAINT "milestone_progress_milestone_id_fkey" FOREIGN KEY ("milestone_id") REFERENCES "milestones" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "milestone_progress" ADD CONSTRAINT "milestone_progress_form_submission_id_fkey" FOREIGN KEY ("form_submission_id") REFERENCES "form_submissions" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE "milestone_progress" ADD CONSTRAINT "milestone_progress_completed_by_fkey" FOREIGN KEY ("completed_by") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE "files_metadata" ADD CONSTRAINT "files_metadata_milestone_submission_id_fkey" FOREIGN KEY ("milestone_submission_id") REFERENCES "form_submissions" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "milestone_progress" ADD CONSTRAINT "milestone_progress_reviewed_by_fkey" FOREIGN KEY ("reviewed_by") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "admin_verification_codes" ADD CONSTRAINT "admin_verification_codes_requester_user_id_fkey" FOREIGN KEY ("requester_user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "reviewer_verification_codes" ADD CONSTRAINT "reviewer_verification_codes_requester_user_id_fkey" FOREIGN KEY ("requester_user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "password_change_tokens" ADD CONSTRAINT "fk_password_change_tokens_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "support_messages" ADD CONSTRAINT "support_messages_application_id_fkey" FOREIGN KEY ("application_id") REFERENCES "applications" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "support_messages" ADD CONSTRAINT "support_messages_resolved_by_fkey" FOREIGN KEY ("resolved_by") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
